# Generated by Django 4.1.3 on 2024-04-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('drinks', 'Beverages'), ('lunch', 'Lunch'), ('dinner', 'the evening')], max_length=20, verbose_name='type of food')),
                ('name', models.CharField(max_length=20, verbose_name='food name')),
                ('price', models.PositiveIntegerField(verbose_name='The price of food')),
                ('descripion', models.TextField(verbose_name='Description of food')),
                ('image', models.ImageField(help_text='Images should be in 800x480 size', upload_to='Foods', verbose_name='photo of food')),
                ('slug', models.SlugField(blank=True, help_text='This field is filled automatically', unique=True, verbose_name='Aslag')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('situation', models.BooleanField(default=True, verbose_name='Availability of food')),
                ('status', models.BooleanField(default=False, help_text='Publication status on the site', verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='first name and last name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('text', models.TextField(verbose_name='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('food', models.ForeignKey(help_text='Which food is the comment intended for?', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='food_app.food', verbose_name='Food')),
                ('parent', models.ForeignKey(blank=True, help_text='If this comment is in response to another comment, it will be completed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='food_app.comment', verbose_name='Reply to the comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
