# Generated by Django 4.1.3 on 2024-04-07 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='title')),
                ('body', models.TextField(verbose_name='text')),
                ('image', models.ImageField(help_text='The size of the images should be 470x570 pixels', upload_to='Blog', verbose_name='blog image')),
                ('situation', models.BooleanField(default=False, verbose_name='publication status')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='creation date')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Update history')),
                ('slug', models.SlugField(blank=True, help_text='this field is filled automatically', verbose_name='aslag')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='writer')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Category title')),
                ('slug', models.SlugField(blank=True, help_text='This field is filled automatically', verbose_name='Aslag')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'Grouping',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='Title tag')),
                ('slug', models.SlugField(blank=True, help_text='This field is filled automatically', unique=True, verbose_name='Aslag')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='first name and last name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('text', models.TextField(verbose_name='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('blog', models.ForeignKey(help_text='What article is the intended comment for?', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog', verbose_name='Article')),
                ('parent', models.ForeignKey(blank=True, help_text='If this comment is in response to another comment, it will be completed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.comment', verbose_name='Reply to the comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog_app.category', verbose_name='grouping'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='blog_app.tag', verbose_name='tags'),
        ),
    ]
